# Generated by Django 4.2.2 on 2023-10-10 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recommendation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceTbl',
            fields=[
                ('preferenceId', models.CharField(default=recommendation.models.generate_preference_key, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('preferredAnimalType', models.CharField(max_length=20)),
                ('preferredAge', models.IntegerField()),
                ('preferredGender', models.CharField(max_length=20)),
                ('preferredSpayed', models.BooleanField()),
                ('preferredNeutered', models.BooleanField()),
                ('preferredHealthCondition', models.CharField(max_length=50)),
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityPreferenceTbl',
            fields=[
                ('personalitypfId', models.CharField(default=recommendation.models.generate_personality_preference_key, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('personality', models.CharField(max_length=50)),
                ('preferenceId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recommendation.preferencetbl')),
            ],
        ),
        migrations.CreateModel(
            name='ColorPreferenceTbl',
            fields=[
                ('colorpfId', models.CharField(default=recommendation.models.generate_color_preference_key, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('color', models.CharField(max_length=20)),
                ('preferenceId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recommendation.preferencetbl')),
            ],
        ),
        migrations.CreateModel(
            name='BreedPreferenceTbl',
            fields=[
                ('breedpfId', models.CharField(default=recommendation.models.generate_breed_preference_key, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('breed', models.CharField(max_length=50)),
                ('preferenceId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recommendation.preferencetbl')),
            ],
        ),
    ]
