# Generated by Django 4.2.7 on 2023-11-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_application_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='inPersonVisitTime',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='interviewTime',
            field=models.CharField(default='', max_length=20),
        ),
    ]
