# Generated by Django 4.2.7 on 2023-11-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_application_inpersonvisittime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='picture',
            field=models.ImageField(default='static/default.png', upload_to='static/application_pics'),
        ),
    ]
