# Generated by Django 4.2.7 on 2023-11-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='preferredBreed',
            field=models.CharField(choices=[('Puspin', 'Puspin'), ('Aspin', 'Aspin'), ('Any', 'Any')], default='Any', max_length=20),
        ),
        migrations.AlterField(
            model_name='preference',
            name='preferredAge',
            field=models.CharField(choices=[('Puppy/Kitten', 'Puppy/Kitten'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior'), ('Any', 'Any')], default='', max_length=20),
        ),
    ]
