# Generated by Django 4.2.2 on 2023-10-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
