# Generated by Django 4.2.2 on 2023-11-18 08:47

from django.db import migrations, models
import donation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donationId', models.CharField(default=donation.models.generate_donation_key, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('donationAmount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='FundraisingCampaign',
            fields=[
                ('campaignId', models.CharField(default=donation.models.generate_campaign_key, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('campaignName', models.CharField(max_length=50, unique=True)),
                ('campaignDescription', models.TextField(blank=True, max_length=500, null=True)),
                ('campaignGoal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('campaignImage', models.ImageField(upload_to='static/image/campaign_img')),
            ],
        ),
    ]
